name: Print Software Versions 

on: [push]

jobs:
  PrintLanguageVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version

  PrintDBMSVersion:
    runs-on: ubuntu-latest
    needs: PrintLanguageVersion
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg wget
          wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
          mongosh --version

      - name: Print MongoDB version from service
        run: |
          mongosh --host localhost --eval "printjson(db.version())"
