name: Print Software Versions 

on: [push]

jobs:
  PrintLanguageVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version
  PrintDBMSVersions:
    needs: [PrintLanguageVersion]
    steps:
      - name Print MongoDB version 
        run mongod --version