name: Print Software Versions 

on: [push]

jobs:
  PrintLanguageVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version

  PrintDBMSVersion:
    runs-on: ubuntu-latest
    needs: PrintLanguageVersion
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..20}; do
            if mongo --host localhost --eval "db.version()"; then
              break
            fi
            echo "MongoDB is not ready yet, waiting..."
            sleep 5
          done

      - name: Print MongoDB Version
        run: mongo --host localhost --eval "printjson(db.version())"
