name: Print Software Versions

on:
  push:
    branches: main

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version
      - name: Print Node Version
        run: node --version
      - name: Print Python Version
        run: python --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Install MongoDB
        run: |
          sudo apt-get update
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
      - name: Print PostgreSQL Version
        run: psql --version
      - name: Print MySQL Version
        run: mysql -V
      - name: Print MongoDB Version
        run: mongod --version
